config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'tasks/:id/complete', to: 'tasks#complete', as: 'task_complete'

  resources :tasks, only: %i[index show]

  root 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    has_many :user_tasks
    has_many :users, through: :user_tasks

    def completed_for?(user)
        user_task = self.user_tasks.find_by(user: user)

        user_task.present? && user_task.completed
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_tasks
  has_many :tasks, through: :user_tasks
end

app/models/user_task.rb
class UserTask < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!

  def index
    @tasks = Task.all
  end

  def complete
    task = Task.find(params[:id])

    # Task.find_or_create_by(user: current_user, task: task)
    user_task = task.user_tasks.find_by(user: current_user)

    if user_task == nil
      UserTask.create(user: current_user, task: task, completed: true)
    else
      # Existe el user_task

      # if user_task.completed
      #   user_task.completed = false
      # else
      #   user_task.completed = true
      # end
      user_task.completed = !user_task.completed

      user_task.save
    end

    redirect_to tasks_path
  end

  def show
    @task = Task.find(params[:id])
    @user_tasks = UserTask.where(task: @task).order(updated_at: :desc).limit(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prueba2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Bucket List del 18</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <% if user_signed_in? %>
                <li class="nav-item">
                    <%= image_tag current_user.photo, class: 'img-perfil img-fluid' %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete %>
                </li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/tasks/index.html.erb
<div class="row">
    <% @tasks.each do |task| %>
        <div class="col-md-4">
            <%= image_tag task.photo, class: 'img-fluid' %>
            <h1>
                <%= link_to task.title, task_path(id: task.id) %>
            </h1>
            <p><%= task.description %></p>
            <% if task.completed_for?(current_user) %>
                <%= link_to "No listo", task_complete_path(id: task.id), class: 'btn btn-danger' %>
            <% else %>
                <%= link_to "Listo", task_complete_path(id: task.id), class: 'btn btn-success' %>
            <% end %>
        </div>
    <% end %>
</div>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<ul>
    <% @user_tasks.each do |user_task| %>
        <li><%= user_task.user.email %></li> 
    <% end %>
</ul>